# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c120e89ab78bb4cd2a701c8f7a875e3306783380392f69c6f73c0c2358d46722eb46b011c5f47388f0b94bd6c6c77aaccd6ee9326ee71eda36f9b0443804f8d

test:
  secret_key_base: aaeab4fda631ab2308fb4a49c3388816777350b35649cbceeeeaec52696dda5b716095da651a65ad2664b5b2b57b136b9d5dad881bfa01521989d9575fc62ed2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
